export const TABLE_NAMES = [
  "users",
  "groups",
  "group_members",
  "boards",
  "layouts",
  "items",
  "item_layouts",
  "apps",
  "app_tags",
  "integrations",
  "integration_secrets",
  "server_settings",
  "user_credentials",
  "roles",
  "role_permissions",
  "user_roles",
  "group_roles",
  "board_user_permissions",
  "board_group_permissions",
  "jobs",
  "oidc_identities",
  "oidc_group_mappings",
  "oidc_secrets",
  "audit_logs",
  "auth_sessions",
  "automation_rules",
  "automation_runtime_state",
  "automation_runs",
  "notifications",
  "incidents",
  "incident_events",
  "push_subscriptions",
  "status_pages",
  "status_page_services",
  "maintenance_windows",
  "maintenance_window_targets",
  "service_slos",
] as const;

export const BOARD_VISIBILITIES = ["private", "authenticated", "public"] as const;
export const STATUS_PAGE_VISIBILITIES = ["private", "public"] as const;
export const MAINTENANCE_WINDOW_STATUSES = [
  "scheduled",
  "active",
  "completed",
  "cancelled",
] as const;
export const USER_STATUSES = ["active", "disabled"] as const;
export const INTEGRATION_STATUSES = ["unknown", "available", "unavailable"] as const;
export const APP_HEALTH_STATUSES = ["unknown", "up", "down", "timeout", "error"] as const;
export const JOB_TYPES = ["heartbeat"] as const;
export const JOB_STATUSES = ["queued", "running", "succeeded", "failed"] as const;

export type DatabaseDialect = "sqlite" | "postgres";
export type BoardVisibility = (typeof BOARD_VISIBILITIES)[number];

export const SCHEMA_CONTRACT = {
  users: [
    "id",
    "username",
    "usernameCanonical",
    "email",
    "displayName",
    "status",
    "isSystemAdmin",
    "authVersion",
  ],
  groups: ["id", "name", "description"],
  group_members: ["groupId", "userId"],
  boards: ["id", "slug", "name", "visibility", "ownerUserId", "revision"],
  layouts: ["id", "boardId", "name", "breakpoint", "columns", "rowHeight", "sortOrder"],
  items: ["id", "boardId", "widgetType", "widgetVersion", "integrationId"],
  item_layouts: ["id", "itemId", "layoutId", "x", "y", "w", "h"],
  apps: ["id", "name", "url", "target", "healthStatus", "healthConfigRevision", "integrationId"],
  app_tags: ["appId", "value", "canonicalValue"],
  integrations: ["id", "type", "name", "baseUrl", "status", "createdBy", "configRevision"],
  integration_secrets: ["id", "integrationId", "key", "ciphertext", "iv", "authTag", "keyVersion"],
  server_settings: [
    "id",
    "schemaVersion",
    "instanceName",
    "onboardingCompleted",
    "oidcEnabled",
    "oidcIssuer",
    "oidcClientId",
    "oidcDisplayName",
    "oidcScopes",
    "oidcRedirectUri",
    "oidcGroupClaim",
    "oidcAutoLinkVerifiedEmail",
    "oidcAutoProvision",
    "oidcAllowLocalLogin",
  ],
  user_credentials: ["userId", "passwordHash", "passwordUpdatedAt"],
  roles: ["id", "name", "description"],
  role_permissions: ["roleId", "permission"],
  user_roles: ["userId", "roleId"],
  group_roles: ["groupId", "roleId"],
  board_user_permissions: ["boardId", "userId", "permission"],
  board_group_permissions: ["boardId", "groupId", "permission"],
  jobs: [
    "id",
    "type",
    "status",
    "scheduledAt",
    "startedAt",
    "finishedAt",
    "attempt",
    "errorCode",
    "errorMessageSafe",
    "metadataJson",
  ],
  oidc_identities: ["id", "userId", "issuer", "subject", "email", "createdAt", "updatedAt"],
  oidc_group_mappings: ["id", "oidcGroup", "localGroupId", "createdAt"],
  oidc_secrets: ["id", "ciphertext", "iv", "authTag", "keyVersion", "createdAt", "updatedAt"],
  audit_logs: [
    "id",
    "actorUserId",
    "action",
    "targetType",
    "targetId",
    "outcome",
    "metadataJson",
    "ip",
    "userAgent",
    "sessionIdHash",
    "createdAt",
  ],
  auth_sessions: [
    "id",
    "userId",
    "createdAt",
    "lastSeenAt",
    "expiresAt",
    "revokedAt",
    "userAgent",
    "ip",
  ],
  automation_rules: [
    "id",
    "name",
    "description",
    "enabled",
    "ownerUserId",
    "triggerType",
    "triggerConfigJson",
    "conditionConfigJson",
    "actionType",
    "actionConfigJson",
    "cooldownSeconds",
    "configRevision",
    "lastEnabledAt",
    "createdAt",
    "updatedAt",
  ],
  automation_runtime_state: [
    "automationId",
    "nextRunAt",
    "lastTriggeredAt",
    "lastCompletedAt",
    "lastObservedState",
    "failureCount",
    "leaseOwner",
    "leaseUntil",
  ],
  automation_runs: [
    "id",
    "automationId",
    "runKey",
    "triggerType",
    "status",
    "scheduledFor",
    "startedAt",
    "finishedAt",
    "actionType",
    "errorCode",
    "resourceId",
    "summaryJson",
    "createdAt",
  ],
  notifications: [
    "id",
    "userId",
    "category",
    "severity",
    "title",
    "body",
    "sourceType",
    "sourceId",
    "sourceIntegrationId",
    "dedupKey",
    "destinationPath",
    "readAt",
    "dismissedAt",
    "expiresAt",
    "createdAt",
    "updatedAt",
  ],
  incidents: [
    "id",
    "integrationId",
    "kind",
    "severity",
    "status",
    "openedAt",
    "lastChangedAt",
    "resolvedAt",
    "openingEventId",
    "closingEventId",
    "createdAt",
    "updatedAt",
  ],
  incident_events: ["id", "incidentId", "eventType", "summary", "createdAt"],
  push_subscriptions: [
    "id",
    "userId",
    "endpointHash",
    "endpointCiphertext",
    "endpointIv",
    "endpointAuthTag",
    "p256dhCiphertext",
    "p256dhIv",
    "p256dhAuthTag",
    "authCiphertext",
    "authIv",
    "authAuthTag",
    "keyVersion",
    "userAgent",
    "disabledAt",
    "createdAt",
    "updatedAt",
  ],
  status_pages: [
    "id",
    "name",
    "slug",
    "description",
    "visibility",
    "enabled",
    "createdBy",
    "configRevision",
    "createdAt",
    "updatedAt",
  ],
  status_page_services: [
    "id",
    "statusPageId",
    "sourceIntegrationId",
    "displayName",
    "description",
    "sortOrder",
    "showIncidentHistory",
    "createdAt",
    "updatedAt",
  ],
  maintenance_windows: [
    "id",
    "name",
    "description",
    "startsAt",
    "endsAt",
    "status",
    "createdBy",
    "createdAt",
    "updatedAt",
  ],
  maintenance_window_targets: ["maintenanceId", "integrationId"],
  service_slos: [
    "id",
    "serviceKey",
    "name",
    "objectiveBasisPoints",
    "windowDays",
    "excludeMaintenance",
    "enabled",
    "configRevision",
    "createdAt",
    "updatedAt",
  ],
} as const satisfies Record<(typeof TABLE_NAMES)[number], readonly string[]>;
