export const BACKUP_TABLE_NAMES = [
  "users",
  "groups",
  "group_members",
  "boards",
  "layouts",
  "items",
  "item_layouts",
  "apps",
  "app_tags",
  "integrations",
  "integration_secrets",
  "server_settings",
  "user_credentials",
  "roles",
  "role_permissions",
  "user_roles",
  "group_roles",
  "board_user_permissions",
  "board_group_permissions",
  "jobs",
  "oidc_identities",
  "oidc_group_mappings",
  "oidc_secrets",
  "automation_rules",
  "status_pages",
  "status_page_services",
  "maintenance_windows",
  "maintenance_window_targets",
  "service_slos",
  "slo_alert_policies",
  "service_dependencies",
] as const;

export type BackupTableName = (typeof BACKUP_TABLE_NAMES)[number];

export const TABLE_INSERT_ORDER = [
  "server_settings",
  "users",
  "groups",
  "roles",
  "user_credentials",
  "group_members",
  "role_permissions",
  "user_roles",
  "group_roles",
  "integrations",
  "boards",
  "apps",
  "integration_secrets",
  "layouts",
  "app_tags",
  "items",
  "item_layouts",
  "board_user_permissions",
  "board_group_permissions",
  "jobs",
  "oidc_identities",
  "oidc_group_mappings",
  "oidc_secrets",
  "automation_rules",
  "status_pages",
  "status_page_services",
  "maintenance_windows",
  "maintenance_window_targets",
  "service_slos",
  "slo_alert_policies",
  "service_dependencies",
] as const satisfies readonly BackupTableName[];

export const TABLE_DELETE_ORDER = [...TABLE_INSERT_ORDER].reverse();

export const BACKUP_COLUMNS = {
  users: [
    "id",
    "username",
    "usernameCanonical",
    "email",
    "displayName",
    "status",
    "isSystemAdmin",
    "authVersion",
    "createdAt",
    "updatedAt",
    "lastLoginAt",
  ],
  groups: ["id", "name", "description", "createdAt", "updatedAt"],
  group_members: ["groupId", "userId", "createdAt"],
  boards: [
    "id",
    "slug",
    "name",
    "description",
    "visibility",
    "ownerUserId",
    "themeJson",
    "settingsJson",
    "revision",
    "createdAt",
    "updatedAt",
  ],
  layouts: [
    "id",
    "boardId",
    "name",
    "breakpoint",
    "columns",
    "rowHeight",
    "sortOrder",
    "createdAt",
    "updatedAt",
  ],
  items: [
    "id",
    "boardId",
    "widgetType",
    "widgetVersion",
    "title",
    "configJson",
    "integrationId",
    "createdAt",
    "updatedAt",
  ],
  item_layouts: ["id", "itemId", "layoutId", "x", "y", "w", "h", "minW", "minH", "maxW", "maxH"],
  apps: [
    "id",
    "name",
    "description",
    "url",
    "iconRef",
    "color",
    "healthcheckEnabled",
    "healthcheckConfigJson",
    "target",
    "healthStatus",
    "lastCheckedAt",
    "lastLatencyMs",
    "lastHttpStatus",
    "lastHealthErrorCode",
    "healthConfigRevision",
    "integrationId",
    "createdAt",
    "updatedAt",
  ],
  app_tags: ["appId", "value", "canonicalValue"],
  integrations: [
    "id",
    "type",
    "name",
    "baseUrl",
    "enabled",
    "configJson",
    "status",
    "lastCheckedAt",
    "configRevision",
    "createdBy",
    "createdAt",
    "updatedAt",
  ],
  integration_secrets: [
    "id",
    "integrationId",
    "key",
    "ciphertext",
    "iv",
    "authTag",
    "keyVersion",
    "createdAt",
    "updatedAt",
  ],
  server_settings: [
    "id",
    "schemaVersion",
    "instanceName",
    "onboardingCompleted",
    "oidcEnabled",
    "oidcIssuer",
    "oidcClientId",
    "oidcDisplayName",
    "oidcScopes",
    "oidcRedirectUri",
    "oidcGroupClaim",
    "oidcAutoLinkVerifiedEmail",
    "oidcAutoProvision",
    "oidcAllowLocalLogin",
    "createdAt",
    "updatedAt",
  ],
  user_credentials: ["userId", "passwordHash", "passwordUpdatedAt", "createdAt", "updatedAt"],
  roles: ["id", "name", "description", "createdAt", "updatedAt"],
  role_permissions: ["roleId", "permission"],
  user_roles: ["userId", "roleId"],
  group_roles: ["groupId", "roleId"],
  board_user_permissions: ["boardId", "userId", "permission"],
  board_group_permissions: ["boardId", "groupId", "permission"],
  jobs: [
    "id",
    "type",
    "status",
    "scheduledAt",
    "startedAt",
    "finishedAt",
    "attempt",
    "errorCode",
    "errorMessageSafe",
    "metadataJson",
  ],
  oidc_identities: ["id", "userId", "issuer", "subject", "email", "createdAt", "updatedAt"],
  oidc_group_mappings: ["id", "oidcGroup", "localGroupId", "createdAt"],
  oidc_secrets: ["id", "ciphertext", "iv", "authTag", "keyVersion", "createdAt", "updatedAt"],
  automation_rules: [
    "id",
    "name",
    "description",
    "enabled",
    "ownerUserId",
    "triggerType",
    "triggerConfigJson",
    "conditionConfigJson",
    "actionType",
    "actionConfigJson",
    "cooldownSeconds",
    "configRevision",
    "lastEnabledAt",
    "createdAt",
    "updatedAt",
  ],
  status_pages: [
    "id",
    "name",
    "slug",
    "description",
    "visibility",
    "enabled",
    "createdBy",
    "configRevision",
    "createdAt",
    "updatedAt",
  ],
  status_page_services: [
    "id",
    "statusPageId",
    "sourceIntegrationId",
    "displayName",
    "description",
    "sortOrder",
    "showIncidentHistory",
    "createdAt",
    "updatedAt",
  ],
  maintenance_windows: [
    "id",
    "name",
    "description",
    "startsAt",
    "endsAt",
    "status",
    "createdBy",
    "createdAt",
    "updatedAt",
  ],
  maintenance_window_targets: ["maintenanceId", "integrationId"],
  service_slos: [
    "id",
    "serviceKey",
    "name",
    "objectiveBasisPoints",
    "windowDays",
    "excludeMaintenance",
    "enabled",
    "configRevision",
    "createdAt",
    "updatedAt",
  ],
  slo_alert_policies: [
    "id",
    "sloId",
    "enabled",
    "warningThreshold",
    "criticalThreshold",
    "cooldownSeconds",
    "notifyOnRecovery",
    "configRevision",
    "createdAt",
    "updatedAt",
  ],
  service_dependencies: [
    "id",
    "upstreamServiceKey",
    "downstreamServiceKey",
    "relationship",
    "createdBy",
    "createdAt",
    "updatedAt",
  ],
} as const satisfies Record<BackupTableName, readonly string[]>;

export const JSON_OBJECT_COLUMNS = new Set([
  "configJson",
  "themeJson",
  "settingsJson",
  "metadataJson",
  "triggerConfigJson",
  "actionConfigJson",
]);

export const JSON_OBJECT_OR_NULL_COLUMNS = new Set([
  "healthcheckConfigJson",
  "conditionConfigJson",
]);

export const DATE_COLUMNS = new Set([
  "createdAt",
  "updatedAt",
  "lastLoginAt",
  "lastCheckedAt",
  "passwordUpdatedAt",
  "scheduledAt",
  "startedAt",
  "finishedAt",
  "lastEnabledAt",
  "startsAt",
  "endsAt",
]);

export const BOOLEAN_COLUMNS = new Set([
  "isSystemAdmin",
  "enabled",
  "onboardingCompleted",
  "healthcheckEnabled",
  "oidcEnabled",
  "oidcAutoLinkVerifiedEmail",
  "oidcAutoProvision",
  "oidcAllowLocalLogin",
  "showIncidentHistory",
  "excludeMaintenance",
]);

export const PREVIEW_REDACTED_COLUMNS = new Set(["ciphertext", "iv", "authTag", "passwordHash"]);
