export const BACKUP_TABLE_NAMES = [
  "users",
  "groups",
  "group_members",
  "boards",
  "layouts",
  "items",
  "item_layouts",
  "apps",
  "app_tags",
  "integrations",
  "integration_secrets",
  "server_settings",
  "user_credentials",
  "roles",
  "role_permissions",
  "user_roles",
  "group_roles",
  "board_user_permissions",
  "board_group_permissions",
  "jobs",
] as const;

export type BackupTableName = (typeof BACKUP_TABLE_NAMES)[number];

export const TABLE_INSERT_ORDER = [
  "server_settings",
  "users",
  "groups",
  "roles",
  "user_credentials",
  "group_members",
  "role_permissions",
  "user_roles",
  "group_roles",
  "integrations",
  "boards",
  "apps",
  "integration_secrets",
  "layouts",
  "app_tags",
  "items",
  "item_layouts",
  "board_user_permissions",
  "board_group_permissions",
  "jobs",
] as const satisfies readonly BackupTableName[];

export const TABLE_DELETE_ORDER = [...TABLE_INSERT_ORDER].reverse();

export const BACKUP_COLUMNS = {
  users: [
    "id",
    "username",
    "usernameCanonical",
    "email",
    "displayName",
    "status",
    "isSystemAdmin",
    "authVersion",
    "createdAt",
    "updatedAt",
    "lastLoginAt",
  ],
  groups: ["id", "name", "description", "createdAt", "updatedAt"],
  group_members: ["groupId", "userId", "createdAt"],
  boards: [
    "id",
    "slug",
    "name",
    "description",
    "visibility",
    "ownerUserId",
    "themeJson",
    "settingsJson",
    "revision",
    "createdAt",
    "updatedAt",
  ],
  layouts: [
    "id",
    "boardId",
    "name",
    "breakpoint",
    "columns",
    "rowHeight",
    "sortOrder",
    "createdAt",
    "updatedAt",
  ],
  items: [
    "id",
    "boardId",
    "widgetType",
    "widgetVersion",
    "title",
    "configJson",
    "integrationId",
    "createdAt",
    "updatedAt",
  ],
  item_layouts: ["id", "itemId", "layoutId", "x", "y", "w", "h", "minW", "minH", "maxW", "maxH"],
  apps: [
    "id",
    "name",
    "description",
    "url",
    "iconRef",
    "color",
    "healthcheckEnabled",
    "healthcheckConfigJson",
    "target",
    "healthStatus",
    "lastCheckedAt",
    "lastLatencyMs",
    "lastHttpStatus",
    "lastHealthErrorCode",
    "healthConfigRevision",
    "integrationId",
    "createdAt",
    "updatedAt",
  ],
  app_tags: ["appId", "value", "canonicalValue"],
  integrations: [
    "id",
    "type",
    "name",
    "baseUrl",
    "enabled",
    "configJson",
    "status",
    "lastCheckedAt",
    "configRevision",
    "createdBy",
    "createdAt",
    "updatedAt",
  ],
  integration_secrets: [
    "id",
    "integrationId",
    "key",
    "ciphertext",
    "iv",
    "authTag",
    "keyVersion",
    "createdAt",
    "updatedAt",
  ],
  server_settings: [
    "id",
    "schemaVersion",
    "instanceName",
    "onboardingCompleted",
    "createdAt",
    "updatedAt",
  ],
  user_credentials: ["userId", "passwordHash", "passwordUpdatedAt", "createdAt", "updatedAt"],
  roles: ["id", "name", "description", "createdAt", "updatedAt"],
  role_permissions: ["roleId", "permission"],
  user_roles: ["userId", "roleId"],
  group_roles: ["groupId", "roleId"],
  board_user_permissions: ["boardId", "userId", "permission"],
  board_group_permissions: ["boardId", "groupId", "permission"],
  jobs: [
    "id",
    "type",
    "status",
    "scheduledAt",
    "startedAt",
    "finishedAt",
    "attempt",
    "errorCode",
    "errorMessageSafe",
    "metadataJson",
  ],
} as const satisfies Record<BackupTableName, readonly string[]>;

export const JSON_OBJECT_COLUMNS = new Set([
  "configJson",
  "themeJson",
  "settingsJson",
  "metadataJson",
]);

export const JSON_OBJECT_OR_NULL_COLUMNS = new Set(["healthcheckConfigJson"]);

export const DATE_COLUMNS = new Set([
  "createdAt",
  "updatedAt",
  "lastLoginAt",
  "lastCheckedAt",
  "passwordUpdatedAt",
  "scheduledAt",
  "startedAt",
  "finishedAt",
]);

export const BOOLEAN_COLUMNS = new Set([
  "isSystemAdmin",
  "enabled",
  "onboardingCompleted",
  "healthcheckEnabled",
]);

export const PREVIEW_REDACTED_COLUMNS = new Set(["ciphertext", "iv", "authTag", "passwordHash"]);
